import { Category } from '../types/category';
import { Goal } from '../types/goal';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat_fitness',
    name: 'Fitness & Health',
    color: '#10b981',
    icon: 'Activity',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat_study',
    name: 'Study & Learning',
    color: '#3b82f6',
    icon: 'BookOpen',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat_coding',
    name: 'Coding & Projects',
    color: '#8b5cf6',
    icon: 'Code2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat_personal',
    name: 'Mindset & Habits',
    color: '#f59e0b',
    icon: 'Smile',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat_finance',
    name: 'Finance & Career',
    color: '#06b6d4',
    icon: 'DollarSign',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_GOALS: Goal[] = [
  {
    id: 'goal_study',
    name: 'Study & Research',
    description: 'Deep work study or course lectures',
    categoryId: 'cat_study',
    type: 'duration',
    target: 6,
    unit: 'hours',
    frequency: 'daily',
    active: true,
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'goal_workout',
    name: 'Daily Workout',
    description: 'Gym session, run, or stretching',
    categoryId: 'cat_fitness',
    type: 'boolean',
    target: 1,
    unit: 'done',
    frequency: 'daily',
    active: true,
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'goal_steps',
    name: 'Daily Steps',
    description: 'Walking and movement target',
    categoryId: 'cat_fitness',
    type: 'numeric',
    target: 10000,
    unit: 'steps',
    frequency: 'daily',
    order: 3,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'goal_reading',
    name: 'Book Reading',
    description: 'Non-fiction reading',
    categoryId: 'cat_personal',
    type: 'duration',
    target: 30,
    unit: 'minutes',
    frequency: 'daily',
    active: true,
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'goal_coding',
    name: 'DSA / LeetCode Problems',
    description: 'Algorithms and problem solving practice',
    categoryId: 'cat_coding',
    type: 'count',
    target: 5,
    unit: 'problems',
    frequency: 'daily',
    active: true,
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
